orbs: # declare what orbs we are going to use
    node: circleci/node@4.2.1 # the node orb provides common node-related configuration

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
    build:
        working_directory: ~/repo
        executor: node/default

        # Primary container image where all commands run

        docker:
            - image: cimg/node:current
              auth:
                  username: mydockerhub-user
                  password: $DOCKERHUB_PASSWORD

        steps:
            - checkout
            - run: 
                  name: Updating System
                  command: sudo apt-get update
            # Install the latest npm - the node Orb takes care of it
            - node/install-npm
            # Install dependencies - the node Orb take care of installation and dependency caching
            - node/install-packages:
                  app-dir: ~/repo
                  cache-path: node_modules
                  override-ci-command: npm i
            - run: 
                  name: Test
                  command: npm run test
